services:
  inbox:
    container_name: inbox
    build: .
    ports:
      - "33883:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./.secrets.toml:/app/.secrets.toml